saga
NStegura/saga pull request #1
Opened 2024-10-07 13:00 UTC by NStegura

2024-10-17 11:36 UTC, NStegura commented
outbox вынес в либу и уже залил в master
tgbot @order_edu_bot

2024-10-17 22:01 UTC, Bazys requested changes
одинаковый код, лежит в разных частях
точно надо такую структуру проекта?
может все таки один cmd и подпапки в нем и вся логика в internal

2024-10-17 22:01 UTC, Bazys commented on orders/internal/app/server/server.go
> +		err = ctx.Err()
и что с этой ошибкой делать дальше?

2024-10-17 22:01 UTC, Bazys commented on orders/internal/app/consumers/consumer.go
> +	ctx         context.Context
Использование `context.Context` внутри структуры или в качестве поля в структуре, как правило, не рекомендуется в Go по нескольким причинам. Чтобы понять, почему это происходит, необходимо немного рассказать о том, что такое `context.Context` и как он должен использоваться.  
  
### Что такое `context.Context`?  
  
`context.Context` - это тип в стандартной библиотеке Go, который обеспечивает передачу дедлайнов, сигналов отмены и других значений, связанных с запросами, между различными интерфейсами API и процессами. Он часто передается в качестве первого аргумента функциям и методам, которые выполняют сетевые вызовы, запросы к базам данных или иным образом должны обрабатывать отмены и тайм-ауты.  
  
### Почему встраивание `context.Context` в структуру является плохой практикой  
  
1. **Управление жизненным циклом**: `context.Context` предназначен для создания и передачи по стеку вызовов. Он привязан к жизненному циклу запроса или операции. Встраивание его в структуру может сделать управление жизненным циклом контекста неясным, поскольку структуры часто имеют иной жизненный цикл, чем отдельный запрос или операция.  
  
2. **Изменяемость**: Контекст `context.Context` должен быть неизменяемым; после создания он не должен быть изменен. Размещение его в структуре подразумевает, что он может быть изменен, поскольку поля структуры, как правило, являются изменяемыми.  
  
3. **Антипаттерн**: В Go принято передавать контекст в качестве первого аргумента функции, а не хранить его. Таким образом, область применения и назначение контекста становятся ясными. Встраивая его в структуру, вы скрываете его использование и делаете код менее читабельным и идиоматичным.  
  
4. **Проблемы параллелизма**: Контексты безопасны для использования несколькими горутинами одновременно. Если контекст встраивается в структуру, которая является общей для всех горутин, то это может привести к некорректному использованию, если контекст будет отменен или его значения будут изменены одновременно.  
  
5. **Тестирование и сопровождение**: Тестирование функций, использующих контекст, переданный в качестве аргумента, не вызывает затруднений. Вы можете предоставить контекст, специально предназначенный для тестового сценария. Если же контекст встроен в структуру, то, возможно, придется инстанцировать или имитировать всю структуру, что может оказаться громоздким и хрупким.  
  
6. **Dependency Injection**: Встраивание контекста в структуру препятствует возможности использования DI для передачи контекстов, что может усложнить тестирование и многократное использование компонентов.  
  
7. **Документация и четкость**: Когда контекст передается в качестве аргумента, понятно, что работа функции может знать об отмене, сроках и т.д. При встраивании семантика становится менее ясной, и разработчику сложнее понять предполагаемое поведение, просто взглянув на сигнатуру функции.  
  
### Лучшие практики  
  
- Всегда передавайте `context.Context` в качестве первого параметра функции или метода, если функция/метод этого требует.  
- Не храните `context.Context` в структуре; вместо этого передавайте его явно там, где это необходимо.  
- Используйте значения контекста только для данных, скопированных на запрос, которые передаются через процессы и API, а не для передачи необязательных параметров в функции.  
  
### Обучение концепции  
  
При обучении концепции `context.Context` важно начать с ее предполагаемого использования и того, как она согласуется с философией явности и читабельности Go. Покажите примеры правильного использования контекста и сравните их с примерами, в которых контекст встроен в структуру. Обсудите практические последствия, особенно в части параллелизма и проектирования API. Поощряйте студентов следовать установленным шаблонам Go и обращаться к стандартной библиотеке Go за примерами идиоматического использования.  

Ссылки:

- [https://go.dev/blog/context-and-structs](https://go.dev/blog/context-and-structs)
- [https://golangbyexample.com/using-context-in-golang-complete-guide](https://golangbyexample.com/using-context-in-golang-complete-guide)
- [Golang context best practices](https://www.golangprograms.com/golang-context-best-practices.html#:~:text=There%20are%20several%20best%20practices,network%20requests%20or%20database%20queries)

2024-10-17 22:01 UTC, Bazys commented on orders/internal/services/order/irepository.go
> +type OrderStateRepository interface {
снаружи выглядит как `order.OrderStateRepository` может достаточно `order.StateRepository`

2024-10-17 22:01 UTC, Bazys commented on orders/internal/clients/redis/cache.go
> +			return
вот тут вообще логики не увидел

2024-10-17 22:01 UTC, Bazys commented on orders/internal/app/consumers/handlers/product/handler.go
> +		if message.Status == models.FAILED {
такой каскад ифчиков в го меняют на case
https://go.dev/doc/effective_go#switch

2024-10-20 13:09 UTC, NStegura commented
"одинаковый код, лежит в разных частях
точно надо такую структуру проекта?
может все таки один cmd и подпапки в нем и вся логика в internal"

да, можно было бы сделать все в одном и это было бы даже быстрее
но идея именно разбить на сервисы в одном репозитории, те каждый сервис рассматривается как отдельный репозиторий со своим дэбагом, окружением и тд
их спокойно можно вынести в отдельные репо со своими энвами и запустить взаимодействие уже на средах

2024-10-24 07:13 UTC, NStegura commented
![image](https://github.com/user-attachments/assets/52fb402d-bf0d-4891-8206-22d3ec53d513)
![image](https://github.com/user-attachments/assets/b84419fc-4872-4e97-8cde-3a5c53204755)
![image](https://github.com/user-attachments/assets/caaccb52-20f1-4126-b093-d5cfe1306942)
![image](https://github.com/user-attachments/assets/2130d2d4-33a0-4709-97f2-fa0836dfc273)

2024-10-24 20:21 UTC, Bazys requested changes
абсолютно одинкаковые ошибки расскиданы по всему коду. на те что я прошлый раз указал, ты исправил, а остальные не трогал
Это опять же к вопросу о неправильной структуре проекта

2024-10-24 20:21 UTC, Bazys commented on orders/internal/storage/repo/order/order.go
> +type OrderRepo struct {
again `order.OrderRepo`

2024-10-24 20:21 UTC, Bazys commented on orders/internal/services/order/models/models.go
> +	CREATED OrderMessageStatus = "CREATED"
в го не принято в верхнем регистре называть

2024-10-24 20:21 UTC, Bazys commented on payments/internal/app/consumer/consumer.go
> +	ctx         context.Context
опять контекст в структуре!

2024-10-24 20:21 UTC, Bazys commented on products/internal/services/product/service.go
> +	} else {
вот опять одинаковые ошибки
у тебя есть return зачем удыу

и это опять к вопросу о повторяющемся коде

ты по многу раз делаешь одни и те же ошибки

2024-10-24 20:21 UTC, Bazys commented on products/internal/services/product/service.go
> +	if status == true {
зачем так?

2024-10-27 18:39 UTC, NStegura commented
Не понимаю, зачем меня валить на мелочах, когда у меня горят дедлайны и я выполняю буквально все замечания + постоянно говорить про неправильную структуру проекта.
Зачем?
Мы обсуждали, что такая структура сделана специально, в этом проекте находятся 4 подпроекта (products, payments, orders, tgbot + отдельно golibs), как если бы они лежали в своих репозиториях
Конечно, код будет повторяться, а времени на учебный проект не очень много - это не работа, чтобы вообще все вынести в либы.
Saga работает, есть tgbot, написаны либы, написаны тесты, сколько можно тянуть со сдачей? 
Просто не понимаю.

2024-10-30 17:04 UTC, merged